train_images: /Users/srmedinac/Documents/BMEPhD/code/data/tumor_budding/256/patches/train/all
train_masks: /Users/srmedinac/Documents/BMEPhD/code/data/tumor_budding/256/masks/train/all
val_images: /Users/srmedinac/Documents/BMEPhD/code/data/tumor_budding/256/patches/val/all
val_masks: /Users/srmedinac/Documents/BMEPhD/code/data/tumor_budding/256/masks/val/all
test_images: /Users/srmedinac/Documents/BMEPhD/code/data/tumor_budding/256/patches/test/all
test_masks: /Users/srmedinac/Documents/BMEPhD/code/data/tumor_budding/256/masks/test/all
batch_size: 32
epochs: 50
num_workers: 12
debug: False
test_only: True
checkpoint_path: /Users/srmedinac/Documents/BMEPhD/code/checkpoints/model-epoch=27-val_loss=0.25.ckpt
continue_from_checkpoint: False
class_weights: False
